//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.08 at 04:38:27 PM PDT 
//


package org.apache.geronimo.system.plugin.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.geronimo.kernel.repository.Artifact;


/**
 * 
 *                 
 *                 Refers to either another module running in the server, or
 *                 an entry in the server's Repository.  In either case this effectively uses a
 *                 URI.
 * 
 *                 When this is pointing to a repository entry, the URI must have a form
 *                 acceptable to the repository, which is currently a URI consisting of
 *                 Maven-style identifiers separated by slashes (groupId/artifactId/version/type,
 *                 for example, the URI "postgresql/postgresql-8.0-jdbc/313/jar" for a file like
 *                 "repository/postgresql/postgresql-8.0-jdbc-313.jar").
 * 
 *                 When this is pointing to a module, the URI should match the
 *                 module's moduleId.  This also looks
 *                 like a Maven-style URI discussed above.
 * 
 *                 The artifactType element can take either a straight URI (as in the examples
 *                 above), or maven-style identifier fragments (groupId, type, artifactId, and
 *                 version), which it will compose into a URI by adding up the fragments with
 *                 slashes in between.
 * 
 *                 There is a correspondence between the xml format and a URI.  For example, the URI
 * 
 *                 postgresql/postgresql-8.0-jdbc/313/jar
 * 
 *                 corresponds to the xml:
 * 
 *                 <groupId>postgresql</groupId>
 *                 <artifactId>postgresql-8.0-jdbc</artifactId>
 *                 <version>313</version>
 *                 <type>jar</type>
 * 	            
 *             
 * 
 * <p>Java class for artifactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="artifactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "artifactType", propOrder = {
    "groupId",
    "artifactId",
    "version",
    "type"
})
public class ArtifactType
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected String groupId;
    @XmlElement(required = true)
    protected String artifactId;
    protected String version;
    protected String type;

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the artifactId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifactId() {
        return artifactId;
    }

    /**
     * Sets the value of the artifactId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifactId(String value) {
        this.artifactId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ArtifactType that = (ArtifactType) o;

        if (artifactId != null ? !artifactId.equals(that.artifactId) : that.artifactId != null) return false;
        if (groupId != null ? !groupId.equals(that.groupId) : that.groupId != null) return false;
        if (type != null ? !type.equals(that.type) : that.type != null) return false;
        if (version != null ? !version.equals(that.version) : that.version != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = groupId != null ? groupId.hashCode() : 0;
        result = 31 * result + (artifactId != null ? artifactId.hashCode() : 0);
        result = 31 * result + (version != null ? version.hashCode() : 0);
        result = 31 * result + (type != null ? type.hashCode() : 0);
        return result;
    }
    
    public Artifact toArtifact() {
        return new Artifact(groupId, artifactId, version, type);
    }

    public static ArtifactType newArtifactType(Artifact artifact) {
        ArtifactType artifactType = new ArtifactType();
        artifactType.setGroupId(artifact.getGroupId());
        artifactType.setArtifactId(artifact.getArtifactId());
        if (artifact.getVersion() != null) {
            artifactType.setVersion(artifact.getVersion().toString());
        }
        artifactType.setType(artifact.getType());
        return artifactType;
    }
}
