

#pragma prefix "geronimo.apache.org"


module corba {
   module test {
	  interface HelloObject {
	  	
	  	void hello0();
	  	void hello1(in short s);
	  	void hello2(in long l);
	  	void hello3(in string s);
	  	void hello4(in wstring s);
	  	
	  	short hello10();
	  	long hello11();
	  	string hello12();
	  	wstring hello13();
	  	
	  };   
   };
};
