// PIDL for CosTSInteroperation Module, p 10-59 
// CORBAservices, Transaction Service V1.0, 3/94

#include "geronimo-orb.idl"
#include <IOP.idl>
#include <CosTransactions.idl>

#pragma prefix "omg.org"


module CosTSInteroperation {
	const IOP::ComponentId TAG_TRANSACTION_POLICY=26;
	
	struct TransactionPolicyComponent {
		CosTransactions::TransactionPolicyValue tpv;
	};
	
	const IOP::ComponentId TAG_OTS_POLICY= 31;
	const IOP::ComponentId TAG_INV_POLICY= 32;
};
