#ifndef _ORB_IDL_
#define _ORB_IDL_

// Some definitions from the CORBA module as needed
// by other modules. This file is for declaration
// purposes only!!

module CORBA
{
	typedef unsigned long ServiceOption;
	typedef unsigned long ServiceDetailType;

	typedef unsigned long PolicyType;

	// actually, Current is pseudo, but we need it this way so everything compiles
	interface Current {};
	
	interface Policy
	{
		readonly attribute PolicyType policy_type;
		Policy copy();
		void destroy();
	};
};
#endif // _ORB_IDL_
