#!/bin/sh
##
## $Rev$ $Date$
##

PROGNAME=`basename "$0"`
DIRNAME=`dirname "$0"`

# OS specific support (must be 'true' or 'false').
cygwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
esac

# Translate PWD into a Windows path for better compatibility
if $cygwin ; then
    PWD=`cygpath --windows $PWD`
fi

ant $BUILD_OPTIONS -emacs -logger org.apache.tools.ant.NoBannerLogger -f bootstrap.xml "$@"

