#!/bin/sh
##
## $Id$
##

PROGNAME=`basename "$0"`
DIRNAME=`dirname "$0"`

warn() {
    echo "${PROGNAME}: $*"
}

die() {
    warn "$*"
    exit 1
}

now() {
    date +'%H:%M:%S %Z %Y'
}

begin() {
    warn "Starting multi-stage build..."
}

abort() {
    die "Aborted ($startdate to `now`)"
}

complete() {
    if [ "$1" == "0" ]; then
        warn "Completed ($startdate to `now`)"
    else
        die "Failed ($startdate to `now`)"
    fi
}

main() {
    startdate=`now`
    
    trap abort STOP KILL INT ABRT
    
    (
        begin && (
            mvn -Dstage=bootstrap "$@" && \
            mvn -Dstage=assemble "$@"
        ) && complete $?
    )
    
    exit 0
}

main "$@" | 2>&1 tee build.log

