//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.23 at 08:34:08 PM PDT 
//


package org.apache.geronimo.deployment.service.plan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                         gbeanType includes all the elements defined in
 *                         abstract-serviceType.
 *                     
 * 
 * <p>Java class for gbeanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gbeanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}attributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="xml-attribute" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}xml-attributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="references" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}referencesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="xml-reference" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}xml-attributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dependency" type="{http://geronimo.apache.org/xml/ns/deployment-1.2}patternType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gbeanType", propOrder = {
    "attribute",
    "xmlAttribute",
    "reference",
    "references",
    "xmlReference",
    "dependency"
})
public class GbeanType {

    protected List<AttributeType> attribute;
    @XmlElement(name = "xml-attribute")
    protected List<XmlAttributeType> xmlAttribute;
    protected List<ReferenceType> reference;
    protected List<ReferencesType> references;
    @XmlElement(name = "xml-reference")
    protected List<XmlAttributeType> xmlReference;
    protected List<PatternType> dependency;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "class", required = true)
    protected String clazz;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeType }
     * 
     * 
     */
    public List<AttributeType> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<AttributeType>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the xmlAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXmlAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlAttributeType }
     * 
     * 
     */
    public List<XmlAttributeType> getXmlAttribute() {
        if (xmlAttribute == null) {
            xmlAttribute = new ArrayList<XmlAttributeType>();
        }
        return this.xmlAttribute;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReference() {
        if (reference == null) {
            reference = new ArrayList<ReferenceType>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the references property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferencesType }
     * 
     * 
     */
    public List<ReferencesType> getReferences() {
        if (references == null) {
            references = new ArrayList<ReferencesType>();
        }
        return this.references;
    }

    /**
     * Gets the value of the xmlReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXmlReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlAttributeType }
     * 
     * 
     */
    public List<XmlAttributeType> getXmlReference() {
        if (xmlReference == null) {
            xmlReference = new ArrayList<XmlAttributeType>();
        }
        return this.xmlReference;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatternType }
     * 
     * 
     */
    public List<PatternType> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<PatternType>();
        }
        return this.dependency;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

}
