//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.26 at 10:44:48 AM PDT 
//


package org.apache.geronimo.security.deployment.model.security;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.geronimo.security.deployment.model.security package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CredentialStore_QNAME = new QName("http://geronimo.apache.org/xml/ns/security-2.0", "credential-store");
    public final static QName _Security_QNAME = new QName("http://geronimo.apache.org/xml/ns/security-2.0", "security");
    private final static QName _DefaultSubject_QNAME = new QName("http://geronimo.apache.org/xml/ns/security-2.0", "default-subject");
    private final static QName _SecurityRef_QNAME = new QName("http://geronimo.apache.org/xml/ns/security-2.0", "security-ref");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.geronimo.security.deployment.model.security
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoleMappingsType }
     * 
     */
    public RoleMappingsType createRoleMappingsType() {
        return new RoleMappingsType();
    }

    /**
     * Create an instance of {@link DistinguishedNameType }
     * 
     */
    public DistinguishedNameType createDistinguishedNameType() {
        return new DistinguishedNameType();
    }

    /**
     * Create an instance of {@link SecurityRefType }
     * 
     */
    public SecurityRefType createSecurityRefType() {
        return new SecurityRefType();
    }

    /**
     * Create an instance of {@link PrincipalType }
     * 
     */
    public PrincipalType createPrincipalType() {
        return new PrincipalType();
    }

    /**
     * Create an instance of {@link LoginDomainPrincipalType }
     * 
     */
    public LoginDomainPrincipalType createLoginDomainPrincipalType() {
        return new LoginDomainPrincipalType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link RealmPrincipalType }
     * 
     */
    public RealmPrincipalType createRealmPrincipalType() {
        return new RealmPrincipalType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link SubjectInfoType }
     * 
     */
    public SubjectInfoType createSubjectInfoType() {
        return new SubjectInfoType();
    }

    /**
     * Create an instance of {@link SecurityType }
     * 
     */
    public SecurityType createSecurityType() {
        return new SecurityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/security-2.0", name = "credential-store")
    public JAXBElement<String> createCredentialStore(String value) {
        return new JAXBElement<String>(_CredentialStore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/security-2.0", name = "security")
    public JAXBElement<SecurityType> createSecurity(SecurityType value) {
        return new JAXBElement<SecurityType>(_Security_QNAME, SecurityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/security-2.0", name = "default-subject")
    public JAXBElement<SubjectInfoType> createDefaultSubject(SubjectInfoType value) {
        return new JAXBElement<SubjectInfoType>(_DefaultSubject_QNAME, SubjectInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/security-2.0", name = "security-ref")
    public JAXBElement<SecurityRefType> createSecurityRef(SecurityRefType value) {
        return new JAXBElement<SecurityRefType>(_SecurityRef_QNAME, SecurityRefType.class, null, value);
    }

}
