//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.26 at 10:42:23 AM PDT 
//


package org.apache.geronimo.security.deployment.model.loginconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.geronimo.security.deployment.model.loginconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public final static QName _LoginConfig_QNAME = new QName("http://geronimo.apache.org/xml/ns/loginconfig-2.0", "login-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.geronimo.security.deployment.model.loginconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link LoginConfigType }
     * 
     */
    public LoginConfigType createLoginConfigType() {
        return new LoginConfigType();
    }

    /**
     * Create an instance of {@link LoginModuleRefType }
     * 
     */
    public LoginModuleRefType createLoginModuleRefType() {
        return new LoginModuleRefType();
    }

    /**
     * Create an instance of {@link LoginModuleType }
     * 
     */
    public LoginModuleType createLoginModuleType() {
        return new LoginModuleType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/loginconfig-2.0", name = "login-config")
    public JAXBElement<LoginConfigType> createLoginConfig(LoginConfigType value) {
        return new JAXBElement<LoginConfigType>(_LoginConfig_QNAME, LoginConfigType.class, null, value);
    }

}
