//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 10:50:34 AM PDT 
//


package org.apache.geronimo.tomcat.deployment.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.geronimo.components.jaspi.model.AuthModuleType;
import org.apache.geronimo.components.jaspi.model.ConfigProviderType;
import org.apache.geronimo.components.jaspi.model.ServerAuthConfigType;
import org.apache.geronimo.components.jaspi.model.ServerAuthContextType;


/**
 * <p>Java class for authenticationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{http://geronimo.apache.org/xml/ns/geronimo-jaspi}configProvider"/>
 *         &lt;element ref="{http://geronimo.apache.org/xml/ns/geronimo-jaspi}serverAuthConfig"/>
 *         &lt;element ref="{http://geronimo.apache.org/xml/ns/geronimo-jaspi}serverAuthContext"/>
 *         &lt;element ref="{http://geronimo.apache.org/xml/ns/geronimo-jaspi}serverAuthModule"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticationType", propOrder = {
    "configProvider",
    "serverAuthConfig",
    "serverAuthContext",
    "serverAuthModule"
})
public class AuthenticationType extends org.apache.geronimo.web25.deployment.model.AuthenticationType {

    @XmlElement(namespace = "http://geronimo.apache.org/xml/ns/geronimo-jaspi")
    protected ConfigProviderType configProvider;
    @XmlElement(namespace = "http://geronimo.apache.org/xml/ns/geronimo-jaspi")
    protected ServerAuthConfigType serverAuthConfig;
    @XmlElement(namespace = "http://geronimo.apache.org/xml/ns/geronimo-jaspi")
    protected ServerAuthContextType serverAuthContext;
    @XmlElement(namespace = "http://geronimo.apache.org/xml/ns/geronimo-jaspi")
    protected AuthModuleType serverAuthModule;

    /**
     * Gets the value of the configProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigProviderType }
     *     
     */
    public ConfigProviderType getConfigProvider() {
        return configProvider;
    }

    /**
     * Sets the value of the configProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigProviderType }
     *     
     */
    public void setConfigProvider(ConfigProviderType value) {
        this.configProvider = value;
    }

    /**
     * Gets the value of the serverAuthConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ServerAuthConfigType }
     *     
     */
    public ServerAuthConfigType getServerAuthConfig() {
        return serverAuthConfig;
    }

    /**
     * Sets the value of the serverAuthConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerAuthConfigType }
     *     
     */
    public void setServerAuthConfig(ServerAuthConfigType value) {
        this.serverAuthConfig = value;
    }

    /**
     * Gets the value of the serverAuthContext property.
     * 
     * @return
     *     possible object is
     *     {@link ServerAuthContextType }
     *     
     */
    public ServerAuthContextType getServerAuthContext() {
        return serverAuthContext;
    }

    /**
     * Sets the value of the serverAuthContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerAuthContextType }
     *     
     */
    public void setServerAuthContext(ServerAuthContextType value) {
        this.serverAuthContext = value;
    }

    /**
     * Gets the value of the serverAuthModule property.
     * 
     * @return
     *     possible object is
     *     {@link AuthModuleType }
     *     
     */
    public AuthModuleType getServerAuthModule() {
        return serverAuthModule;
    }

    /**
     * Sets the value of the serverAuthModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthModuleType }
     *     
     */
    public void setServerAuthModule(AuthModuleType value) {
        this.serverAuthModule = value;
    }

}
