//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 10:50:34 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geronimo.apache.org/xml/ns/j2ee/web/tomcat-2.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.apache.geronimo.tomcat.deployment.model;
