//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 10:50:34 AM PDT 
//


package org.apache.geronimo.tomcat.deployment.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.geronimo.web25.deployment.model.ContainerConfigType;


/**
 * <p>Java class for tomcat-configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tomcat-configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cross-context" type="{http://geronimo.apache.org/xml/ns/web/tomcat/config-1.0}emptyType2" minOccurs="0"/>
 *         &lt;element name="disable-cookies" type="{http://geronimo.apache.org/xml/ns/web/tomcat/config-1.0}emptyType2" minOccurs="0"/>
 *         &lt;element name="valve-chain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listener-chain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tomcat-realm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="manager" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cluster" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tomcat-configType", namespace = "http://geronimo.apache.org/xml/ns/web/tomcat/config-1.0", propOrder = {
    "host",
    "crossContext",
    "disableCookies",
    "context",
    "valveChain",
    "listenerChain",
    "tomcatRealm",
    "manager",
    "cluster"
})
public class TomcatConfigType extends ContainerConfigType {

    protected String host;
    @XmlElement(name = "cross-context")
    protected EmptyType crossContext;
    @XmlElement(name = "disable-cookies")
    protected EmptyType disableCookies;
    protected ContextType context;
    @XmlElement(name = "valve-chain")
    protected String valveChain;
    @XmlElement(name = "listener-chain")
    protected String listenerChain;
    @XmlElement(name = "tomcat-realm")
    protected String tomcatRealm;
    protected String manager;
    protected String cluster;

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the crossContext property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType2 }
     *     
     */
    public EmptyType getCrossContext() {
        return crossContext;
    }

    /**
     * Sets the value of the crossContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType2 }
     *     
     */
    public void setCrossContext(EmptyType value) {
        this.crossContext = value;
    }

    /**
     * Gets the value of the disableCookies property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType2 }
     *     
     */
    public EmptyType getDisableCookies() {
        return disableCookies;
    }

    /**
     * Sets the value of the disableCookies property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType2 }
     *     
     */
    public void setDisableCookies(EmptyType value) {
        this.disableCookies = value;
    }

    /**
     * Gets the value of the context property.
     *
     * @return
     *     possible object is
     *     {@link ContextType }
     *
     */
    public ContextType getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     *
     * @param value
     *     allowed object is
     *     {@link ContextType }
     *
     */
    public void setContext(ContextType value) {
        this.context = value;
    }

    /**
     * Gets the value of the valveChain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValveChain() {
        return valveChain;
    }

    /**
     * Sets the value of the valveChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValveChain(String value) {
        this.valveChain = value;
    }

    /**
     * Gets the value of the listenerChain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListenerChain() {
        return listenerChain;
    }

    /**
     * Sets the value of the listenerChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListenerChain(String value) {
        this.listenerChain = value;
    }

    /**
     * Gets the value of the tomcatRealm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomcatRealm() {
        return tomcatRealm;
    }

    /**
     * Sets the value of the tomcatRealm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomcatRealm(String value) {
        this.tomcatRealm = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManager(String value) {
        this.manager = value;
    }

    /**
     * Gets the value of the cluster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCluster() {
        return cluster;
    }

    /**
     * Sets the value of the cluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCluster(String value) {
        this.cluster = value;
    }

}
