
#include "CosNaming.idl"

/* 
 * resolve_host is a custom API that lets the name service send back a logical hostname for
 * a component, which then can be resolved by the server for clustering and loadbalancing
 */

module org
{
    module apache
    {
        module geronimo
        {
            module interop
            {
                module rmi
                {
                    module iiop
                    {
                        interface NameService : ::CosNaming::NamingContextExt
                        {
                            string resolve_host(in string host);
                        };
                    };
                };
            };
        };
    };
};
