/*

Copyright 1995 AT&T Global Information Solutions Company
Copyright 1995 Digital Equipment Corporation
Copyright 1995 Expersoft Corporation
Copyright 1995 Groupe Bull
Copyright 1995 Hewlett-Packard Company
Copyright 1995 IBM (in collaboration with Taligent, Inc.)
Copyright 1995 International Computers Limited
Copyright 2002 Object Management Group, Inc.
Copyright 1997 Netscape Communications Corporation
Copyright 1997 Northern Telecom LImited
Copyright 1995 Novell, Inc.
Copyright 1995 Siemens Nixdorf Informationssysteme AG
Copyright 1995, 1997 SunSoft, Inc.
Copyright 1995 Tandem Computer Inc. (in collaboration with Odyssey Research Assoc., Inc.)
Copyright 1995 Tivoli Systems, Inc.
Copyright 1997 Visigenic Software, Inc.

The companies listed above have granted to the Object Management Group, Inc. (OMG) a nonexclusive, royalty-free, paid up,
worldwide license to copy and distribute this document and to modify this document and distribute copies of the modified version.
Each of the copyright holders listed above has agreed that no person shall be deemed to have infringed the copyright in
the included material of any such copyright holder by reason of having used the specification set forth herein or having conformed
any computer software to the specification.

PATENT

The attention of adopters is directed to the possibility that compliance with or adoption of OMG specifications may require use
of an invention covered by patent rights. OMG shall not be responsible for identifying patents for which a license may be
required by any OMG specification, or for conducting legal inquiries into the legal validity or scope of those patents that are
brought to its attention. OMG specifications are prospective and advisory only. Prospective users are responsible for protecting
themselves against liability for infringement of patents.

*/

#ifndef _SSLIOP_IDL
#define _SSLIOP_IDL
#pragma prefix "omg.org"
#include <IOP.idl>
#include<Security.idl>

module SSLIOP {
	// Security mechanism SSL

	const IOP::ComponentId TAG_SSL_SEC_TRANS = 20;

	struct SSL {
		Security::AssociationOptions target_supports;
		Security::AssociationOptions target_requires;
		unsigned short port;
	};
};
#endif /* _SSLIOP_IDL */
