
CREATE TABLE USERS 
(
  PASSWORD VARCHAR(255),
  USERNAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (USERNAME)
);

CREATE TABLE ACCOUNTS
(
  STATUS VARCHAR(30)
);
  
CREATE TABLE SEQUENCE_TABLE
(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  DUMMY INT
);

CREATE TABLE ADDRESSES
(
  ID INT NOT NULL, 
  ZIPCODE VARCHAR(255),
  STATE VARCHAR(255),
  STREETNAME2 VARCHAR(255),
  STREETNAME1 VARCHAR(255),
  COUNTRY VARCHAR(255),
  CITY VARCHAR(255)
);
