//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.26 at 10:40:10 AM PDT 
//


package org.apache.geronimo.security.deployment.model.credentialstore;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.geronimo.security.deployment.model.credentialstore package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public final static QName _CredentialStore_QNAME = new QName("http://geronimo.apache.org/xml/ns/credentialstore-1.0", "credential-store");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.geronimo.security.deployment.model.credentialstore
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link CredentialType }
     * 
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link CredentialStoreType }
     * 
     */
    public CredentialStoreType createCredentialStoreType() {
        return new CredentialStoreType();
    }

    /**
     * Create an instance of {@link RealmType }
     * 
     */
    public RealmType createRealmType() {
        return new RealmType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialStoreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/credentialstore-1.0", name = "credential-store")
    public JAXBElement<CredentialStoreType> createCredentialStore(CredentialStoreType value) {
        return new JAXBElement<CredentialStoreType>(_CredentialStore_QNAME, CredentialStoreType.class, null, value);
    }

}
